- src/app.module.ts
- src/modules/system/user-group/entities/user-group.entity.ts
- src/modules/system/user-group/user-group.module.ts
- src/modules/system/user-role/controllers/user-role.controller.ts
- src/modules/system/user-role/user-role.module.ts
This commit will add user, user role and user group module in the
app.module.ts
> feat: 🎸 added user, user role and user group modules in app mod

- src/app.module.ts
- src/modules/system/user-role/entities/user-role.entity.ts
- src/modules/system/user/entities/user.entity.ts
This commit will add relationship between user, user role and user group
> feat: 🎸 added relationship between user with roles and groups

- src/app.module.ts
- src/modules/system/user-authority/controllers/user-authority.controller.ts
- src/modules/system/user-authority/entities/user-authority.entity.ts
- src/modules/system/user-authority/services/user-authority.service.ts
- src/modules/system/user-authority/user-authority.module.ts
- src/modules/system/user-role/entities/user-role.entity.ts
This commit will add support for user authorities for every user role
> feat: 🎸 added support for user authorities

- src/core/controllers/base.contoller.ts
- src/core/services/base.service.ts
- src/modules/app/controllers/apps.controller.ts
This commit will add support to update the entities in the following
criteria: if the entity payload contains the uid of the item already
exist in the database then the item will be updated otherwise it will be
created.
> refactor: 💡 modified the updation process of the entities

- src/core/entities/user-core-props.entity.ts
- src/modules/dashboard/entities/dashboard-chart.entity.ts
- src/modules/form/entities/sqlview.ts
- src/modules/message/entities/message.entity.ts
- src/modules/record/entities/data-store.entity.ts
- src/modules/report/entities/report.entity.ts
- src/modules/system/user-authority/entities/user-authority.entity.ts
- src/modules/system/user-role/entities/user-role.entity.ts
- src/modules/system/user/entities/user-settings.entity.ts
- src/modules/system/user/entities/user.entity.ts
This commit will fix the update error while updating the related
entities i.e one-to-many, many-to-one and many-to-many
> fix: 🐛 resolving update error for entities relationships

- src/modules/system/user/entities/user.entity.ts
This commit will update user entities relationship with other entites
like User Authorities, User Role, User Groups etc.
> refactor: 💡 updated user entities relationships

- src/modules/system/user-authority/entities/user-authority.entity.ts
- src/modules/system/user-role/entities/user-role.entity.ts
This commit will modified relationship between UserRole and
UserAuthorities
> fix: 🐛 modified UserAuthorities and UserRole relationship

- src/modules/system/user-group/entities/user-group.entity.ts
- src/modules/system/user-role/entities/user-role.entity.ts
- src/modules/system/user/entities/user-settings.entity.ts
- src/modules/system/user/entities/user.entity.ts
This commit will update user entity relationship with other entities
> fix: 🐛 updated user entity relationships with other entities

- documents/USERMODULE.md
This commit will update USERMODULE.md for definition of User Entity and
how to perform CRUD operation
> docs: ✏️ updated USERMODULE.md document for the User Entity

- documents/USERGROUPMODULE.md
This commit will create USERGROUPMODULE.md
> docs: ✏️ created USERGROUPMODULE.md

- documents/USERAUTHORITYMODULE.md
This commit will add USERAUTHORITYMODULE.md
> docs: ✏️ added USERAUTHORITYMODULE.md

- README.md
This commit will update README.md
> docs: ✏️ updated README.md

- documents/USERMODULE.md
This commit will update USERMODULE.md
> docs: ✏️ updated USERMODULE.md

- documents/UPDATEENTITYMODULE.md
This commit will add instruction on how to update normal entities
properties as well as the entities with relationships
> docs: ✏️ added UPDATEENTITYMODULE.md

- src/modules/maintenance/field-option/entities/field-option.entity.ts
- src/modules/maintenance/field/entities/field.entity.ts
This commit will update the relationship between the field and field
option
> refactor: 💡 modified field and field option relationship

- src/app.module.ts
- src/modules/form/form.module.ts
- src/modules/maintenance/field-input-type/controllers/field-input-type.controller.ts
- src/modules/maintenance/field-input-type/entities/field-input-type.entity.ts
- src/modules/maintenance/field-input-type/field-input-type.module.ts
- src/modules/maintenance/field-input-type/services/field-input-type.service.ts
- src/modules/maintenance/field-option/services/field-option.service.ts
- src/modules/maintenance/field/entities/field.entity.ts
This commit will modify the field and field input type relationship
> refactor: 💡 modified field and field input type relationship

- src/app.module.ts
- src/modules/form/form.module.ts
- src/modules/maintenance/field-relation/controllers/field-relation.controller.ts
- src/modules/maintenance/field-relation/entities/field-relation.entity.ts
- src/modules/maintenance/field-relation/field-relation.module.ts
- src/modules/maintenance/field-relation/services/field-relation.service.ts
- src/modules/maintenance/field/entities/field.entity.ts
This commit will modify field relation module
> refactor: 💡 modified field relation module

- src/app.module.ts
This commit will update import to the app.module.ts
> chore: 🤖 updated import in app.module.ts

- src/app.controller.ts
- src/app.module.ts
- src/modules/app/apps.module.ts
- src/modules/app/controllers/apps.controller.ts
- src/modules/app/services/apps.service.ts
This commit will resolve the issue while importing app.module.ts
> fix: 🐛 resolved error in importing dependencies in app.module

- src/app.module.ts
- src/app.service.ts
- src/modules/app/apps.module.ts
This commit will add app.service.ts to the app level in the project
> feat: 🎸 added app.service.ts to the app level in the project

- src/app.module.ts
This commit will modify controllers and providers imports
> refactor: 💡 modified controllers and providers import

- .dependabot/config.yml
This commit will updated dependabot configurations
> chore: 🤖 updated dependabot configurations

- .travis.yml
This commit will update the configuration file for the travis ci
> ci: 🎡 updated travisci configuration file

- documents/USERAUTHORITYMODULE.md
- documents/USERGROUPMODULE.md
- documents/USERMODULE.md
- documents/USERROLEMODULE.md
This commit will update documentation by removing the uid referencing to
id in all referencing entities
> docs: ✏️ changed in docs uid definition for referencing to id

- src/core/controllers/base.contoller.ts
- src/core/helpers/response.helper.ts
This commit will add support to remove id in from the API response payload during sending GET and
POST request
> fix(response): added support by removing id in API response

- src/modules/training/services/training-session.service.ts
I added checks for when topics, facilitators and participants are empty
> refactor: add checks for  empty properties
